#%RAML 1.0 ResourceType
post:
  description: post order of <<resourcePathName>>
  responses:
    201:
      body:
        application/json:
          example:
            {
    "serverTime":"12/12/19 16:20:11",
             "gainingTodayCount":"2",
             "losingTodayCount":"2",
             "totalGainAndLossAmount":"0.00",
             "dayGainAndLossAmount":"-4910.00",
             "averagePrice":"1560.15",
             "exchange":"CNC",
             "markToMarketPrice":"-182.70",
             "lastTradedPrice":"1550.00",
             "tradingSymbol":"RELIANCE",
             "calculatedNetQuantity":"18.0",
             "averageBuyPrice":"1560.15",
             "averageSellPrice":"0.00",
             "boughtPrice":"28082.70",
             "buyQuantity":"18",
             "netPositionValue":"-182.70",
             "netQuantity":"18",
             "netValue":"-182.70",
             "soldValue":"0.00",
             "transactionType":"Sell",
             "realizedGainAndLoss":"0.00",
             "unrealizedGainAndLoss":"-182.70"
            }
